### ISSUE TITLE
Make box86 and box86-pi-apps conflict

### ISSUE THREAD

**Issue by Botspot** [Itai-Nelken/weekly-box86-debs#1]
```
dpkg: error processing archive /var/cache/apt/archives/box86_0.2.3+20210830.389927dc-1_armhf.deb (--unpack):
 trying to overwrite '/etc/binfmt.d/box86.conf', which is also in package box86-pi-apps 0.2.3+20210830.389927dc-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/box86_0.2.3+20210830.389927dc-1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Also consider renaming your package to something more meaningful like "box86-no-binfmt".

**Comment by Itai-Nelken** [comment]
I'll add `box86` as a conflicting package to `box86-pi-apps` and also the other way round.

`box86-no-binfmt` isn't a good name in my opinion: it implies that binfmt isn't included so box86 isn't called automatically. that isn't true of course.
we will have to decide on a name before adding it to pi-apps.

**Comment by Botspot** [comment]
I think the name `box86-pi-apps` is misleading. It's not a package specifically for pi-apps, it's a package that does not restart binfmt.
How about **`box86-no-restart-binfmt`**? It's a bit long, but is an accurate description.

**Comment by Itai-Nelken** [comment]
I changed the name to `box86-no-binfmt-restart` and added `box86` as a conflicting package. `box86` now also conflicts with `box86-no-binfmt-restart`.
