### ISSUE TITLE
Doesn't build box64 any more?

### ISSUE THREAD

**Issue by castaway** [Itai-Nelken/weekly-box86-debs#14]
Back when this was the script https://github.com/Itai-Nelken/box86-2deb-weekly-script .. it seems you built box86 and box64, are the box64 builds somewhere else I'm not seeing them now?

**Comment by ryanfortner** [comment]
See https://github.com/ryanfortner/box64-debs.

**Comment by castaway** [comment]
ooh! didnt see that one, mebbe we can get a link to that on the main "how to install" box86 page. and the one from here? Thanks!

**Comment by Itai-Nelken** [comment]
I tried building box64 when it was just released, but had problems with dependencies.
So yes, use @ryanfortner' repository, I will also add it to the website as you suggested.
