### ISSUE TITLE
Make binfmt-restart non-fatal

### ISSUE THREAD

**Issue by Botspot** [Itai-Nelken/weekly-box86-debs#2]
I realized that it is undesirable for a systemd-binfmt restart to be a fatal error under any circumstances.
Plenty of OS'es don't have binfmt, while others don't have it setup corrrectly. These users can still use Box86 just fine.

Consider changing this behavior in your `box86` package so that we don't need two package-names. Then I can transition our Pi-Apps users back to use the `box86` package instead of the `box86-no-binfmt-restart`.

**Comment by Itai-Nelken** [comment]
makes sense, I'll change the `postinst` script to this:
```bash
systemctl restart systemd-binfmt || true
```
sorry for the delay in answering.

**Comment by Botspot** [comment]
Once you do that, please don't take down the box86-no-binfmt-restart package right away - just to be on the safe side.

**Comment by Itai-Nelken** [comment]
I think I'll push a version of `no-binfmt-restart` that is a dummy package that depends on the regualr`box86` package. That way everyone that still has the `no-binfmt-restart` version still gets updates.
I'll also modify the `no-binfmt-restart` `postinst` script to print a message that this package is depracated and instructions on how to remove it and replace it with the new version.

**Comment by Itai-Nelken** [comment]
@Botspot I pushed the first change, the `postinst` script of the box86 package will print a error message if `binfmt` fails to restart with a suggestion to reboot. the return value will still be 0 so the deb will install corretly even if `binfmt` fails to restart.

**Comment by Itai-Nelken** [comment]
there won't be any new builds of the `no-binfmt-restart` package other than a manual one I'll push in a few minutes that will be a dummy package that depends on the box86 package.
you can then make pi-apps `runonce` a script to install the regular `box86` package to mark it as manually installed and then uninstall the `no-binfmt-restart` version.

**Comment by Itai-Nelken** [comment]
all the changes have been pushed.
- The `box86` package won't fail if `binfmt` fails to restart.
- The `no-binfmt-restart` package is a dummy one that simply depends on the regular `box86` package.
- I won't update the `no-binfmt-restart` package anymore as anyone who updates to the latest version will get the regular `box86` package installed.

You can make pi-apps replace the `no-binfmt-restart` package with the regular `box86` one.

**Comment by Botspot** [comment]
> all the changes have been pushed.


Thanks!
