### ISSUE TITLE
No systemd

### ISSUE THREAD

**Issue by mgkahn** [Itai-Nelken/weekly-box86-debs#6]
I am very far out of my knowledge zone so please excuse if this is a silly question. Attempting to install box86 as a precondition of installing wine32 in an Arm64-based Ubuntu image within a Docker container (https://hub.docker.com/r/fredblgr/ubuntu-novnc). That image uses tini as its 'init' process, not systemd as it appears box32 is seeking. How do I proceed to align these two environments? Thanks.

Screen shot below is from a terminal executing in the Ubuntu container.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/3923918/186761514-2d5379db-c8d4-420a-a633-14e1e3825f7d.png">

**Comment by Itai-Nelken** [comment]
systemd is needed for box86 to be called automatically when an x86 binary is executed, it isn't needed to actually use box86. Not having systemd shouldn't be an error, just a warning. I'll see if I can find why the installation is failing for you.
Meanwhile you can try [compiling box86 yourself](https://github.com/ptitSeb/box86/blob/master/docs/COMPILE.md). It isn't too hard and you don't need to wait for a fix.

**Comment by Itai-Nelken** [comment]
There isn't much I can do. The postinstall script isn't failing, systemd is somehow causing the whole installation to fail even though it shouldn't.
The best solution would be to either compile box86 yourself, or extract the binary from the .deb package:
1) Download the latest package (currently newest version is [here](https://github.com/Itai-Nelken/weekly-box86-debs/blob/main/debian/pool/box86_0.2.7%2B20220826.e9fcef3d-1_armhf.deb), click on the download button to download it).
2) Extract the package:
```bash
dpkg-deb -x box86_0.2.7+20220826.e9fcef3d-1_armhf.deb box86_0.2.7+20220826.e9fcef3d-1_armhf
```
The binary will be in `box86_0.2.7+20220826.e9fcef3d-1_armhf/usr/local/bin/box86` 
You can copy the binary to `/usr/local/bin` or any other location on your `PATH`.

**Comment by Itai-Nelken** [comment]
I'm closing this issue as there isn't much I can do, I can't control what systemctl does.. but feel free to ask any questions!

**Comment by mgkahn** [comment]
Sorry to come back after closure. Your first response said: "systemd is needed for box86 to be called automatically when an x86 binary is executed" In the absence of systemd, will wine32 work correctly? My (foggy/limited) understanding is that wine32 will call box86 to do the i386 emulation. Will this need to call box86 by wine32 work without a systemd "trigger"?

**Comment by Itai-Nelken** [comment]
> Sorry to come back after closure.

No problem! Feel free to ask any questions! I closed because It's not a problem on my side (I can't fix systemctl failing if systemd isn't the init process).

>Your first response said: "systemd is needed for box86 to be called automatically when an x86 binary is executed" In the absence of systemd, will wine32 work correctly? My (foggy/limited) understanding is that wine32 will call box86 to do the i386 emulation. Will this need to call box86 by wine32 work without a systemd "trigger"?

Sorry, I missed that part in my reply, I am no wine expert and I'm not sure how it works, but if it starts any processes it won't work without binfmt.

You can check if tini has an equivalent of binfmt and try to set it up yourself. Unfortunately I can't help you there, I have no idea about how binfmt works.

If you have any other questions, feel free to ask them!
